name: 🏷️ Update Package Version and Create Tag
on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  tag:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - name: Set Git User Details
        run: |
          git config user.name "${GITHUB_USER:-github-actions}"
          git config user.email "${GITHUB_EMAIL:-github-actions@github.com}"
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          dry_run: 'true'
      - name: Install project dependencies
        run: yarn --prefer-offline
      - run: yarn run build-checkout
      - run: yarn run build
      - run: git add dist/index.js
      - run: |
          yarn config set version-tag-prefix "v"
          yarn config set version-commit-hooks true
          yarn config set version-git-tag true
          yarn config set version-sign-git-tag false
      - name: Update version
        id: version
        env:
          CHANGELOG: |
            # v%s
            ${{ steps.tag_version.outputs.changelog }}
        run: |
          ## yarn version will update the README with the new tagged version in the examples
          ## and also creates a step output called 'tag' which is the new version
          set -x
          yarn version --patch --message "${CHANGELOG}"

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.tag}}
          release_name: Release ${{steps.version.outputs.tag}}
          body: ${{ steps.tag_version.outputs.changelog }}
